# Generated by Django 5.2.7 on 2026-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="tx_ref",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
