# Generated by Django 5.2.7 on 2026-05-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_tx_ref_alter_payment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="tx_ref",
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt",
            field=models.ImageField(
                blank=True, null=True, upload_to="payment_receipts/"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
