# Generated by Django 5.2.7 on 2026-05-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
