# Generated by Django 5.2.7 on 2026-05-30 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_github_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_courses", models.IntegerField(default=0)),
                ("github_contributions", models.IntegerField(default=0)),
                ("assignments_submitted", models.IntegerField(default=0)),
                ("live_attendance", models.IntegerField(default=0)),
                ("mentor_sessions", models.IntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
