# Generated by Django 5.2.7 on 2026-08-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentreputation",
            name="project_contribution_grade",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentreputation",
            name="project_contributions",
            field=models.IntegerField(default=0),
        ),
    ]
