# Generated by Django 5.2.7 on 2026-08-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_studentreputation_project_contribution_grade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentreputation",
            name="project_contributions",
        ),
    ]
