# Generated by Django 5.2.7 on 2026-06-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codexio_main", "0002_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.BigIntegerField(default=0)),
            ],
        ),
    ]
