# Generated by Django 5.2.7 on 2026-07-09 merge

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codexio_main", "0004_message_delete_conversation"),
        ("codexio_main", "0004_testimonial"),
    ]

    operations = []
