# Generated by Django 5.2.7 on 2025-10-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codexio_main", "0004_message_delete_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="update",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
