# Generated by Django 5.2.7 on 2026-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codexio_main", "0005_merge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="update",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
