# Generated by Django 5.2.7 on 2026-05-12 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_module_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"]},
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("user", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="progress",
            unique_together={("user", "module")},
        ),
    ]
