# Generated by Django 5.2.7 on 2026-05-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_payment_type_updatenotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enrollment_open",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
