# Generated by Django 5.2.7 on 2026-05-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_enrollment_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="class_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="class_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
