# Generated by Django 5.2.7 on 2026-05-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_module_class_date_module_class_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.module",
            ),
        ),
    ]
