# Generated by Django 5.2.7 on 2026-05-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_classsession_meeting_link_moduleaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="discount_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="discount_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
