# Generated by Django 5.2.7 on 2026-05-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_course_discount_active_course_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="first_200_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
