# Generated by Django 5.2.7 on 2026-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_course_first_200_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="discount_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
