# Generated by Django 5.2.7 on 2026-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_mentorrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
