# Generated by Django 5.2.7 on 2026-05-11 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_initial"),
        ("courses", "0003_alter_module_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="course",
        ),
        migrations.AddField(
            model_name="assignment",
            name="module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.module",
            ),
            preserve_default=False,
        ),
    ]
