# Generated by Django 5.2.7 on 2026-05-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_submission_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="file",
        ),
        migrations.AddField(
            model_name="submission",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
