# Generated by Django 5.2.7 on 2026-06-17 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recruiter_name", models.CharField(max_length=100)),
                ("recruiter_email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True)),
                (
                    "level_filter",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "selected_students",
                    models.ManyToManyField(
                        related_name="recruit_requests", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
